<a href="https://colab.research.google.com/github/DayiMarcillo/TAREA/blob/main/about_Numpy_library_Dayana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

aux=np.array([1,2,4])
print(aux)
print('-----------')
# Shape no ayuda a sabes las dimención o froma de la matriz
print(aux.shape)

aux=np.array([[1,2,4],[1,2,4]])
print(aux.shape)
print(aux)
print('-----------')
print(type(aux))

# los crea matrices con únicamente 0
x=np.zeros((4,4))
print('-----------')
print(x)

#full crea matrices con un valor constante en este caso 5
x=np.full((4,4),5)
print('-----------')
print(x)

# eyer crea una matriz de identificación ya que completa la matriz con 0 y en la parte principal lo completa con 1
x=np.eye(4,4)
print('-----------')
print(x)

# Ones se utiliza para crear un array (o matriz) de una forma específica, llena de unos
x=np.ones((4,4))
print('-----------')
print(x)

print(x.shape)

[1 2 4]
-----------
(3,)
(2, 3)
[[1 2 4]
 [1 2 4]]
-----------
<class 'numpy.ndarray'>
-----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-----------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [2]:
# ramdom.random se utiliza para generar un número decimal aleatorio en el rango que es esta caso es de (3,3)
x=10*np.random.random((3,3))
print(x)

[[3.50221877 9.60383032 9.96051919]
 [9.07321031 7.3614175  7.33354977]
 [6.04790478 0.22695672 7.80948756]]


In [3]:
print(x[:2,:2])

[[3.50221877 9.60383032]
 [9.07321031 7.3614175 ]]


In [4]:
print(x[:2,1:3])

[[9.60383032 9.96051919]
 [7.3614175  7.33354977]]


In [5]:
print(x[1,1])

7.361417504743137


In [6]:
print(x[2,2])

7.809487558741676


In [7]:
# ramdom.random se utiliza para generar un número decimal aleatorio en el rango que es esta caso es de (3,3)
x=10*np.random.random((3,3))
print(x)

[[9.50157041 8.57579688 5.10464017]
 [2.15405333 1.14635378 0.53305185]
 [2.87229834 6.09501564 3.98829515]]


In [8]:
# mask se puede utilizar con arrays o matrices para realizar operaciones condicionales.
mask=x>5
print(x[mask])

[9.50157041 8.57579688 5.10464017 6.09501564]


In [9]:
#filter es una función incorporada que se utiliza para filtrar elementos de una secuencia entre un rango
filter=(x>=2)&(x<=4)
print(x[filter])

[2.15405333 2.87229834 3.98829515]


In [10]:
#filter es una función incorporada que se utiliza para filtrar elementos de una secuencia entre un rango
filter=(x>=2)&(x<=4)
print(x[filter])

[2.15405333 2.87229834 3.98829515]


In [11]:
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,5)
integer_array=np.random.randint(0,5,(4,4))
print(integer_array)

[[2 4 2 4]
 [4 2 2 4]
 [2 1 0 3]
 [1 3 4 2]]


***Segunda Parte***

In [12]:
import numpy as np
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(3,4))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
# se imprime la matriz A
print(a)
print("MATRIZ B")
# se imprime la matriz b
print(b)
print("SUMANDO")
# se imprime una matriz sumando la matriz a+b
print(a+b)
print("RESTANDO")
# se imprime una matriz restando la matriz a-b
print(a-b)
print("MULTIPLICANDO")
# se imprime una matriz multiplicando la matriz a*b
print(a*b)
print("___________")

# add se utiliza para realizar la suma de dos arrays o matrices de elemento por elemento.
print(np.add(a,b))
print("___________")

# multiply se utiliza para realizar la multiplicaciones de dos arrays o matrices de elemento por elemento.
print(np.multiply(a,b))
print("___________")

# divide se utiliza para realizar la divisiones de dos arrays o matrices de elemento por elemento.
print(np.divide(a,b))
print("___________")


MATRIZ A
[[3 2 5 9]
 [4 4 4 1]
 [1 4 4 3]]
MATRIZ B
[[6 5 3 4]
 [9 4 7 0]
 [4 7 7 9]]
SUMANDO
[[ 9  7  8 13]
 [13  8 11  1]
 [ 5 11 11 12]]
RESTANDO
[[-3 -3  2  5]
 [-5  0 -3  1]
 [-3 -3 -3 -6]]
MULTIPLICANDO
[[18 10 15 36]
 [36 16 28  0]
 [ 4 28 28 27]]
___________
[[ 9  7  8 13]
 [13  8 11  1]
 [ 5 11 11 12]]
___________
[[18 10 15 36]
 [36 16 28  0]
 [ 4 28 28 27]]
___________
[[0.5        0.4        1.66666667 2.25      ]
 [0.44444444 1.         0.57142857        inf]
 [0.25       0.57142857 0.57142857 0.33333333]]
___________


<ipython-input-12-05e0c2dd3210>:32: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))


In [13]:
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(2,3))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
print(a)
print("MATRIZ B")
print(b)
print("___________")

# dot son multiplica las matrices
print(np.dot(a,b))

MATRIZ A
[[4 1 7]
 [4 3 3]]
MATRIZ B
[[0 5 8 1]
 [5 7 0 7]
 [3 4 4 3]]
___________
[[26 55 60 32]
 [24 53 44 34]]


In [14]:
a=np.random.randint(0,10,(3,3))
print(a)
print("___________")
# a.T intercambia las filas por columnas
print(a.T)

[[1 2 2]
 [4 9 7]
 [3 5 8]]
___________
[[1 4 3]
 [2 9 5]
 [2 7 8]]


In [15]:
a=np.random.randint(0,10,(4,3))
print(a)
print("___________")

b=np.array([1,0,2])
print(b)
print("___________")

# se crea una nueva matriz  utilizando la matriz A y B
c=np.empty_like(a)
print(c)
print("___________")
x=a+b

print(np.empty_like(x))

[[2 1 4]
 [2 6 1]
 [0 6 2]
 [5 3 1]]
___________
[1 0 2]
___________
[[3 2 5]
 [9 4 4]
 [4 1 1]
 [4 4 3]]
___________
[[99400126511993              0              2]
 [             1              0              2]
 [             1              0              2]
 [             1              0              2]]


In [16]:
# FOR se utiliza para realizar un blucle y tiene un rango
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print("___________")


print(b)
print("___________")


print(c)
print("___________")

[[2 1 4]
 [2 6 1]
 [0 6 2]
 [5 3 1]]
___________
[1 0 2]
___________
[[3 1 6]
 [3 6 3]
 [1 6 4]
 [6 3 3]]
___________


In [17]:
b=np.array([1,2,3])
print(b)
print("___________")

# tile se utiliza para replicar la matrices en esta caso se replica la matriz B pero con un rango de 6 veces
x=np.tile(b,(6,1))
print(x)

[1 2 3]
___________
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
a=np.random.randint(20,31,(6,6))
print(a)
print("___________")

print("PROMEDIOS COMPLETOS")
# Mean se utiliza para crear el promedio de la matriz
aux1=np.mean(a)
print(aux1)

print("___________")
print("PROMEDIOS POR FILAS")
# Mean se utiliza para crear el promedio de la matriz pero ahora por fila en este caso la fila 1
aux2=np.mean(a,axis=1)
print(aux2)

[[25 25 25 26 24 22]
 [24 28 22 22 24 25]
 [25 24 29 24 21 23]
 [27 26 25 26 25 24]
 [26 30 28 23 25 30]
 [30 24 25 20 28 28]]
___________
PROMEDIOS COMPLETOS
25.22222222222222
___________
PROMEDIOS POR FILAS
[24.5        24.16666667 24.33333333 25.5        27.         25.83333333]
